# Generated by Django 3.2.5 on 2021-08-25 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
