# Generated by Django 3.2.5 on 2021-08-25 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_article_reporter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='help_line',
            new_name='head_line',
        ),
    ]
