# Generated by Django 3.2.5 on 2021-09-02 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_student_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Student_code',
            new_name='student_code',
        ),
    ]
