# Generated by Django 3.2.5 on 2021-09-02 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_rename_student_code_student_student_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='Student',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='web.Student'),
        ),
    ]
